let greeting = "welcome to JavaScript world";
let Name = "Nithin";
let age = 25;
let concat_ex = Name + " " + "Gowda";
console.log(concat_ex);
let concat_ex1 = Name.concat(" Gowda");
console.log(concat_ex1);
let idx = greeting.indexOf("a");
console.log(idx);
let idxlast = greeting.lastIndexOf("a");
console.log(idxlast);
let sbstrng = greeting.substring(11,22);
console.log(sbstrng);
let lngth = greeting.length;
console.log(lngth);
let slc = greeting.slice(0,8);
console.log(slc);
let splt = greeting.split(" ");
console.log(splt);
